### ISSUE TITLE
Firmware source code missing in repo

### ISSUE THREAD

**Issue by shulter** [talla83/tshw#3]

**Comment by talla83** [comment]
No source code available. 

For protocol information please see a MESA data sheet.
   
REFERENCE INFORMATION
Note that the following interface details presented here are not normally needed for
users, as all register level interface details are handed by the driver code. This information
is presented here for use by interface and driver developers.
SSLBP
GENERAL
SSLBP is a firmware option to HostMot2s SSERIAL serial interface that allows
simple communication to LBP. SSERIAL is a part of the
HostMot2 motion interface firmware for MESA’s Anything-I/O FPGA cards.

**Comment by shulter** [comment]
It would be nice to learn from the source code <3 and tweak the MCU to have different IO, try out debouncing techniques, use LED with serial interfaces..
If you don't want to publish the code please change the GPL license for the firmware.

**Comment by shulter** [comment]
quote from the LICENSE file in the repo:

> Our General Public Licenses are designed to make sure (...) 
> that you receive source code or can get it if you
> want it, that you can change the software or use pieces of it in new
> free programs, and that you know you can do these things.

**Comment by talla83** [comment]
Thank you for the information.
Look here for sourcecode about sserial   
https://github.com/rene-dev/stmbl
https://github.com/rene-dev/stmbl/blob/master/src/comps/sserial.c
